"use client";
import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { Activity, ArrowUpRight, BarChart3, BookOpen, Check, ChevronDown, ChevronRight, CircleHelp, Database, Download, FileText, Layers3, LoaderCircle, Search, Settings2, ShieldCheck, Sparkles, X, AlertTriangle, Landmark, ExternalLink, Menu, MessageSquare, Clock3 } from "lucide-react";
import { ResponsiveContainer, BarChart, Bar, XAxis, YAxis, Tooltip, CartesianGrid, LineChart, Line, Legend } from "recharts";
import { DIMENSIONS, PRESET_QUESTIONS, EVENT_QUESTION, PEER_QUESTION, dimensionQuestion } from "@/lib/research/question-catalog.mjs";
import { retryWindow } from "@/lib/research/retry-after.mjs";
import type { ResearchResult, Evidence, Financial, Claim } from "@/lib/types";

const D:Record<string,string>=DIMENSIONS;
const FACT:Record<string,string>={FACT:"客观事实",INFERENCE:"分析推断",UNKNOWN:"尚待验证"};
const NAV=[{id:"research",name:"研究工作台",icon:Sparkles},{id:"financial",name:"财务与现金流",icon:BarChart3},{id:"peers",name:"同行比较",icon:Landmark},{id:"evidence",name:"证据库",icon:Layers3},{id:"data",name:"数据与方法",icon:Database}];
const QUESTIONS=PRESET_QUESTIONS;
const fmt=(v:number|null|undefined,unit="亿元")=>v===null||v===undefined?"—":unit==="亿元"?(v/1e8).toLocaleString("zh-CN",{minimumFractionDigits:2,maximumFractionDigits:2}):v.toFixed(2);
const pLabel=(v:string)=>v.endsWith("-06-30")?`${v.slice(0,4)} H1`:v;
const raw=(v:unknown)=>typeof v==="number"?v.toLocaleString("zh-CN",{maximumFractionDigits:6}):v===null||v===undefined?"未覆盖":JSON.stringify(v);
function Badge({type}:{type:string}) {return <span className={`badge ${type.toLowerCase()}`}>{FACT[type]??type}</span>;}
function Empty({title,children}:{title:string;children:React.ReactNode}) {return <div className="empty"><CircleHelp size={28}/><h3>{title}</h3><p>{children}</p></div>;}
function Chart({records,kind="income"}:{records:Financial[];kind?:string}) {
  const rows=records.map(r=>({period:pLabel(r.period),收入:r.values.revenue===null?null:r.values.revenue/1e8,归母净利润:r.values.parent_profit===null?null:r.values.parent_profit/1e8,经营现金流:r.values.ocf===null?null:r.values.ocf/1e8}));
  return <div className="chart" role="img" aria-label={kind==="income"?"营业收入半年趋势，单位亿元":"归母利润与现金流半年趋势，单位亿元"}><ResponsiveContainer width="100%" height="100%" minWidth={0} initialDimension={{width:320,height:260}}><BarChart data={rows} barGap={8} margin={{top:16,right:10,left:0,bottom:0}}><CartesianGrid strokeDasharray="4 4" vertical={false} stroke="#e9edf4"/><XAxis dataKey="period" axisLine={false} tickLine={false} tick={{fill:"#7d8799",fontSize:12}}/><YAxis axisLine={false} tickLine={false} tick={{fill:"#7d8799",fontSize:12}} width={50}/><Tooltip cursor={{fill:"#f3f4fb"}} formatter={v=>Number(v).toFixed(2)+" 亿元"}/><Legend iconType="circle" iconSize={8}/>{kind==="income"?<Bar dataKey="收入" fill="#8272dd" radius={[4,4,0,0]} maxBarSize={54}/>:<><Bar dataKey="归母净利润" fill="#8272dd" radius={[4,4,0,0]} maxBarSize={35}/><Bar dataKey="经营现金流" fill="#89c9ba" radius={[4,4,0,0]} maxBarSize={35}/></>}</BarChart></ResponsiveContainer></div>;
}
export default function ResearchApp({initial}:{initial:ResearchResult}) {
  const [result,setResult]=useState(initial),[question,setQuestion]=useState(initial.question),[tab,setTab]=useState("research"),[period,setPeriod]=useState(initial.period),[mode,setMode]=useState("snapshot"),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const [drawer,setDrawer]=useState<Evidence|null>(null),[selected,setSelected]=useState<string[]>([]),[filter,setFilter]=useState("ALL"),[search,setSearch]=useState(""),[settings,setSettings]=useState(false),[access,setAccess]=useState(""),[menu,setMenu]=useState(false),[followup,setFollowup]=useState(""),[traceOpen,setTraceOpen]=useState(false);
  const [status,setStatus]=useState<{financial_configured:boolean;model_configured:boolean;access_protected:boolean;model_provider?:string|null;model?:string|null}>({financial_configured:false,model_configured:initial.model_state==="not_called"||initial.model_state==="active",access_protected:initial.model_state==="not_called"||initial.model_state==="active",model_provider:initial.model_usage?.provider,model:initial.model_usage?.model});
  const [retryAt,setRetryAt]=useState(0),[clock,setClock]=useState(()=>Date.now());
  const retrySeconds=Math.max(0,Math.ceil((retryAt-clock)/1000)),blocked=busy||retrySeconds>0;
  useEffect(()=>{if(!retryAt)return;const tick=()=>{const now=Date.now();setClock(now);if(now>=retryAt)setRetryAt(0);};tick();const timer=setInterval(tick,1000);return()=>clearInterval(timer);},[retryAt]);
  const textarea=useRef<HTMLTextAreaElement>(null),dialog=useRef<HTMLElement>(null),settingsDialog=useRef<HTMLDivElement>(null);
  const current=result.financials.find(r=>r.period===result.period),evidence=result.evidence;
  const counts={POSITIVE:evidence.filter(e=>e.evidence_direction==="POSITIVE").length,NEGATIVE:evidence.filter(e=>e.evidence_direction==="NEGATIVE").length,CONFLICTING:evidence.filter(e=>e.evidence_direction==="CONFLICTING").length,UNKNOWN:evidence.filter(e=>e.claim_type==="UNKNOWN").length};
  const visible=evidence.filter(e=>(filter==="ALL"||(filter==="UNKNOWN"?e.claim_type==="UNKNOWN":e.evidence_direction===filter))&&(!search||`${e.title} ${e.evidence_id} ${e.note}`.toLowerCase().includes(search.toLowerCase())));
  useEffect(()=>{fetch("/api/status").then(r=>r.json()).then(d=>{const s=d as {financial_configured:boolean;model_configured:boolean;access_protected:boolean;model_provider?:string|null;model?:string|null};setStatus(s);}).catch(()=>{});},[]);
  useEffect(()=>{if(!drawer&&!settings)return;const previous=document.activeElement as HTMLElement;const element=drawer?dialog.current:settingsDialog.current;element?.focus();const key=(event:KeyboardEvent)=>{if(event.key==="Escape"){setDrawer(null);setSettings(false);}if(event.key==="Tab"&&element){const items=Array.from(element.querySelectorAll<HTMLElement>('button,input,textarea,select,a[href]')).filter(e=>!e.hasAttribute("disabled"));if(event.shiftKey&&document.activeElement===items[0]){event.preventDefault();items.at(-1)?.focus();}else if(!event.shiftKey&&document.activeElement===items.at(-1)){event.preventDefault();items[0]?.focus();}}};document.addEventListener("keydown",key);return()=>{document.removeEventListener("keydown",key);previous?.focus();};},[drawer,settings]);
  async function run(q=question,asFollowup=false) {
    if(blocked||q.trim().length<2)return;if(status.access_protected&&!access){setSettings(true);setError("请先填写提交者提供的独立站点口令，再开始 AI 研究。");return;}setBusy(true);setError("");setQuestion(q);setTab("research");setSearch("");setFilter("ALL");
    try {
      const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),100000);
      const context=asFollowup||selected.length?{question:result.question,dimensions:result.plan.dimensions,selected_ids:selected,history:result.history}:undefined;
      let response:Response;
      try{response=await fetch("/api/research",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question:q,period,mode,context,...(access?{access_code:access}:{})}),signal:controller.signal});}finally{clearTimeout(timeout);}
      if(response.status===401)setSettings(true);
      if(response.status===429){const window=retryWindow(response.headers.get("Retry-After"));setClock(window.startedAt);setRetryAt(window.retryAt);}
      const data=await response.json() as ResearchResult & {error?:string;message?:string};if(!response.ok)throw new Error(data.error||"研究请求失败。");if(data.status!=="ok")throw new Error(data.message||"当前问题超出研究能力。");
      setResult(data);setSelected(data.selected_ids??[]);setDrawer(null);setFollowup("");
    }catch(e){setError(e instanceof Error?e.message:"网络错误，研究未完成。");}finally{setBusy(false);}
  }
  function showEvidence(id:string) {const found=evidence.find(e=>e.evidence_id===id);if(found)setDrawer(found);}
  function toggle(id:string) {setSelected(s=>s.includes(id)?s.filter(v=>v!==id):[...s.slice(-11),id]);}
  function exportReport() {const blob=new Blob([JSON.stringify({...result,exported_at:new Date().toISOString(),selected_ids:selected},null,2)],{type:"application/json"}),a=document.createElement("a"),url=URL.createObjectURL(blob);a.href=url;a.download=`StockInsight-${result.period}.json`;a.click();URL.revokeObjectURL(url);}
  const filters=<div className="signal-filters">{[["ALL","全部",evidence.length],["POSITIVE","正面",counts.POSITIVE],["NEGATIVE","负面",counts.NEGATIVE],["CONFLICTING","矛盾",counts.CONFLICTING],["UNKNOWN","未知",counts.UNKNOWN]].map(([id,label,count])=><button key={id} className={`${filter===id?"selected":""} ${String(id).toLowerCase()}`} onClick={()=>setFilter(String(id))}>{label}<span>{count}</span></button>)}</div>;
  const cards=(items:Evidence[])=>items.map(e=><button className={`evidence-card ${e.evidence_direction.toLowerCase()}`} key={e.evidence_id} onClick={()=>setDrawer(e)}><div className="evidence-top"><Badge type={e.claim_type}/><span>{e.conflict_kind==="SIGNAL_TENSION"?"信号张力":e.conflict_kind==="SOURCE_CONFLICT"?"来源冲突":D[e.dimension]}</span><ChevronRight size={16}/></div><h3>{e.title}</h3><div className="evidence-value">{e.display_value}</div><p>{e.note||e.calculation_method}</p><div className="evidence-bottom"><span>{pLabel(e.report_period)} · {e.claim_type==="UNKNOWN"?"资料不足":"查看计算依据"}</span><FileText size={14}/></div></button>);
  const claims=result.analysis.claims.map((c:Claim,i:number)=><article className="claim" key={i}><span className="claim-index">{String(i+1).padStart(2,"0")}</span><div><div className="claim-label"><Badge type={c.claim_type}/><span>{result.engine==="llm"?"AI 解读 · 语义待复核":"确定性规则说明"}</span></div><p>{c.rendered_text}</p><div className="citations">{c.evidence_ids.map(id=><button key={id} onClick={()=>showEvidence(id)}><FileText size={12}/>{evidence.find(e=>e.evidence_id===id)?.title??id}<ChevronRight size={12}/></button>)}</div></div></article>);
  const financialSection=<><div className="section-heading"><div><h2>把盈利放回财务趋势里</h2><p>半年累计口径 · 人民币亿元 · 不与全年或单季混用</p></div><span className="soft-tag">可用期次</span></div><div className="charts-grid"><section className="panel chart-panel"><div className="panel-heading"><h3>营业收入</h3><span>亿元</span></div><Chart records={result.financials}/></section><section className="panel chart-panel"><div className="panel-heading"><h3>利润与现金流</h3><span>亿元</span></div><Chart records={result.financials} kind="cash"/></section></div><section className="panel table-panel"><h3>原始财务期次</h3><div className="table-scroll"><table><thead><tr><th>报告期</th><th>营业收入 / 亿元</th><th>归母利润 / 亿元</th><th>扣非归母 / 亿元</th><th>经营现金流 / 亿元</th><th>加权 ROE / %</th></tr></thead><tbody>{result.financials.map(r=><tr key={r.period}><td>{pLabel(r.period)}</td>{["revenue","parent_profit","adjusted_profit","ocf","roe"].map(k=><td key={k}>{fmt(r.values[k],k==="roe"?"%":"亿元")}</td>)}</tr>)}</tbody></table></div><p className="footnote">归母利润与合并经营现金流的股东口径不同，覆盖比值仅为代理。半年 ROE 未年化。</p></section></>;
  return <div className="app-shell"><aside className={`sidebar ${menu?"menu-open":""}`}><Link className="brand" href="/"><span className="brand-icon"><Activity size={24}/></span><span>StockInsight<sup>AI</sup><small>个股诊断 · 证据研究</small></span></Link><div className="workspace-label">RESEARCH WORKSPACE</div><nav aria-label="主要导航">{NAV.map(n=><button key={n.id} className={tab===n.id?"nav-item active":"nav-item"} onClick={()=>{setTab(n.id);setMenu(false);setFilter("ALL");setSearch("");}}><n.icon size={19}/>{n.name}{n.id==="evidence"&&<span className="nav-count">{evidence.length}</span>}</button>)}</nav><div className="sidebar-company"><div className="sidebar-label">当前研究对象</div><div className="company-mini"><span className="company-avatar">M</span><div><b>美的集团</b><small>000333.SZ</small></div><Check size={15}/></div><p>家电制造业</p></div><div className="sidebar-bottom"><div className="trust-note"><ShieldCheck size={20}/><div><b>让结论有据可查</b><p>事实、推断、未知分别呈现</p></div></div><button className="nav-item" onClick={()=>setSettings(true)}><Settings2 size={18}/>连接设置<ChevronRight size={15}/></button><div className="sidebar-footer">研究辅助工具 · 不提供买卖建议</div></div></aside>
  <div className="main-shell"><header className="topbar"><button className="mobile-menu icon-button" aria-label="展开导航" onClick={()=>setMenu(!menu)}><Menu size={22}/></button><div className="breadcrumb">研究空间<ChevronRight size={14}/><span>{NAV.find(n=>n.id===tab)?.name}</span></div><div className="top-actions"><span className="snapshot-label"><Database size={14}/>{result.data_mode==="public_report_snapshot"?"公开财报快照":"授权接口数据"}</span><button className="icon-button" onClick={()=>setSettings(true)} aria-label="连接设置"><Settings2 size={18}/></button><span className="user-avatar">研</span></div></header>
  <main><div className="page-heading"><div><div className="eyebrow">COMPANY RESEARCH</div><div className="company-title"><h1>美的集团</h1><span className="stock-code">000333.SZ</span><span className="industry-tag">家电制造</span></div><p>从经营信号出发，沿真实证据继续研究。</p></div><div className="heading-actions"><label className="period-select"><Clock3 size={15}/><select aria-label="研究报告期" value={period} onChange={e=>{setPeriod(e.target.value);setSelected([]);}}><option value="2026-06-30">2026 半年度</option><option value="2025-06-30">2025 半年度</option><option value="2024-06-30">2024 半年度</option></select><ChevronDown size={14}/></label><button className="secondary-button" onClick={exportReport}><Download size={15}/>导出研究</button></div></div><div className="data-caption"><span><FileText size={13}/>当前结果 {pLabel(result.period)} · 披露 {result.coverage.published_at}</span><span>采集 {result.coverage.retrieved_at.slice(0,10)}{period!==result.period&&" · 新期次将在开始研究后应用"}</span></div>
  <section className="kpi-grid" aria-label="财务概览">{[{label:"营业收入",key:"revenue",suffix:"revenue-yoy"},{label:"归母净利润",key:"parent_profit",suffix:"parent_profit-yoy"},{label:"经营现金流净额",key:"ocf",suffix:"ocf-yoy"}].map(k=>{const yoy=evidence.find(e=>e.evidence_id.endsWith(k.suffix));return <button className="kpi" key={k.key} onClick={()=>{const e=evidence.find(e=>e.evidence_id.endsWith(k.key));if(e)setDrawer(e);else run(QUESTIONS[1]);}}><div className="kpi-label">{k.label}<ArrowUpRight size={15}/></div><div className="kpi-value">{fmt(current?.values[k.key])}<span>亿元</span></div><div className={`kpi-change ${yoy&&yoy.raw_value!==null&&yoy.raw_value<0?"negative-text":"positive-text"}`}>{yoy&&yoy.raw_value!==null?`${yoy.raw_value>=0?"+":""}${yoy.display_value}`:"同口径财报"}<span>{yoy&&yoy.raw_value!==null?"同比":"半年累计"}</span></div></button>;})}<button className="kpi muted-kpi" onClick={()=>run(QUESTIONS[2])}><div className="kpi-label">市盈率 PE TTM<CircleHelp size={15}/></div><div className="kpi-value">{fmt(result.valuations.find(v=>v.thscode==="000333.SZ")?.pe_ttm,"倍")}<span>倍</span></div><div className="kpi-change muted">{result.valuations.length?"授权接口快照":"待接入授权行情与估值"}</div></button></section>
  {result.warnings.some(w=>/超过|失败|拦截|停止/.test(w))&&<div className="data-warnings panel">{result.warnings.filter(w=>/超过|失败|拦截|停止/.test(w)).map((w,i)=><p key={i}>{w}</p>)}</div>}
  {error&&<div className="error-banner" role="alert"><AlertTriangle size={20}/><div><b>本次研究未完成</b><p>{error}</p>{retrySeconds>0&&<p role="status">请在 {retrySeconds} 秒后重试。等待期间保留当前结果，不会自动重复调用。</p>}<small>仍保留上一次成功结果：{result.question}</small></div></div>}
  {tab==="research"&&<><section className="research-panel"><div className="research-heading"><div className="research-icon"><Sparkles size={21}/></div><div><h2>提出一个问题，开始证据研究</h2><p>围绕公司特点选择维度，再用数据验证每一个判断。</p></div><span className="engine-tag">{result.engine==="llm"?`${result.model_usage?.provider??"LLM"} · 本次调用成功`:result.model_state==="failed"?"AI 失败 · 规则结果":status.model_configured?`${status.model_provider??"AI"} 已配置 · 待调用`:"规则研究 · AI 待配置"}</span></div>{status.access_protected&&!access&&<div className="context-strip"><ShieldCheck size={16}/><span>AI 研究需要独立评审口令；公开财报和证据可直接查看。</span><button type="button" onClick={()=>setSettings(true)}>填写口令</button></div>}<form onSubmit={e=>{e.preventDefault();run();}}><textarea ref={textarea} aria-label="研究问题" maxLength={600} value={question} onChange={e=>setQuestion(e.target.value)}/><div className="input-toolbar"><label className="mode-select"><Database size={14}/><select aria-label="数据模式" value={mode} onChange={e=>setMode(e.target.value)}><option value="snapshot">公开财报快照</option><option value="live">扶摇授权接口</option></select></label><button className="primary-button" disabled={blocked||question.trim().length<2} type="submit">{busy?<LoaderCircle size={16} className="spin"/>:<Sparkles size={16}/>} {busy?"正在组织证据…":retrySeconds>0?`${retrySeconds} 秒后可重试`:"开始研究"}</button></div></form><div className="recommended"><span>试着问</span>{QUESTIONS.slice(0,3).map(q=><button disabled={blocked} key={q} onClick={()=>run(q)}>{q}</button>)}</div>{selected.length>0&&<div className="context-strip"><BookOpen size={14}/>已选择 {selected.length} 条证据作为追问上下文<button onClick={()=>setSelected([])}>清除</button></div>}</section>
  <div className="research-body"><div className="results-main"><div className="section-heading"><div><h2>研究结论 <span className="soft-tag">{result.analysis.claims.length} 项观察</span></h2><p>{result.question}</p></div><button className="text-button" onClick={()=>setTraceOpen(!traceOpen)}><Activity size={14}/>研究过程<ChevronDown size={14}/></button></div>{traceOpen&&<section className="panel trace-panel">{result.trace.map((s,i)=><div key={s.step}><span>0{i+1}</span><b>{s.step}</b><small>{s.engine}</small></div>)}<p>{result.plan.rationale}</p>{result.model_usage?.validated_at&&<p>真实模型：{result.model_usage.provider} · {result.model_usage.model} · 规划与解读均已校验 · {result.model_usage.validated_at}</p>}</section>}<section className="panel conclusions"><div className="plan-row"><span>本次重点</span>{result.plan.dimensions.map(d=><span className="dimension-chip" key={d}>{D[d]}</span>)}</div>{claims.length?claims:<Empty title="现有证据不足">请查看未知项，或调整问题。</Empty>}<div className="conclusion-footnote"><ShieldCheck size={14}/>{result.engine==="llm"?"已检查引用、数字及部分主题和财务关系；AI 推断仍需语义复核。":"以上为规则说明。开始研究后按实际模型调用显示 AI 结果或明确的失败原因。"}</div></section>
  <div className="section-heading evidence-heading"><div><h2>证据矩阵</h2><p>点击证据查看原始字段、期次与计算方法</p></div><button className="text-button" onClick={()=>setTab("evidence")}>查看全部<ChevronRight size={14}/></button></div>{filters}<div className="evidence-grid">{cards(visible.slice(0,6))}</div>{!visible.length&&<Empty title="没有发现此类证据">现有资料未发现这一方向的信号，不为凑齐分类生成结论。</Empty>}
  <section className="panel followup-panel"><h3><MessageSquare size={17}/>沿当前证据继续研究</h3><p className="footnote">{result.engine==="llm"?"AI 从本次相关的已校验问题库选择下一步核验问题。":"以下问题来自规则核验问题库。"}</p><div className="followup-suggestions">{result.analysis.followups.map(q=><button key={q} disabled={blocked} onClick={()=>run(q,true)}>{q}<ChevronRight size={14}/></button>)}</div><form onSubmit={e=>{e.preventDefault();run(followup,true);}}><input aria-label="上下文追问" value={followup} onChange={e=>setFollowup(e.target.value)} maxLength={600} placeholder="追问原因、寻找反证，或提出核验问题"/><button disabled={blocked||followup.trim().length<2} className="primary-button">继续研究</button></form></section></div>
  <aside className="research-rail"><section className="panel research-map"><div className="panel-heading"><h3>研究视角</h3><span>6 个维度</span></div><p>针对家电制造业，关注盈利兑现、现金回收与营运效率。</p>{Object.entries(D).map(([key,label],i)=><button className={result.plan.dimensions.includes(key)?"map-row in-plan":"map-row"} key={key} disabled={blocked} onClick={()=>run(dimensionQuestion(key))}><span className="map-number">0{i+1}</span><span>{label}</span>{result.plan.dimensions.includes(key)?<Check size={14}/>:<ChevronRight size={14}/>}</button>)}<div className="map-note">高亮维度来自本次研究计划</div></section><section className="panel source-status"><div className="panel-heading"><h3>数据状态</h3><Database size={16}/></div><div className="status-line"><span>公开财报</span><b className="positive-text">已采集核验</b></div><div className="status-line"><span>行情 / 估值</span><b>{result.valuations.length||result.prices.length?"授权返回":"未接入"}</b></div><div className="status-line"><span>真实 AI 模型</span><b>{result.engine==="llm"?`${result.model_usage?.provider??"LLM"} · 本次成功`:status.model_configured?`${status.model_provider??"AI"} 已配置，需口令`:"未配置"}</b></div><div className="status-line"><span>财报期次</span><b>{pLabel(result.period)}</b></div><div className="status-note"><CircleHelp size={15}/><p>披露有时滞，不展示未经验证的实时价格。</p></div><button className="text-button" onClick={()=>setTab("data")}>查看来源与限制<ChevronRight size={14}/></button></section><section className="event-card"><div className="eyebrow">值得继续核验</div><h3>归母与扣非利润为何分化？</h3><p>半年报提及汇兑及衍生工具分类。持续影响需要附注与后续数据验证。</p><button onClick={()=>run(EVENT_QUESTION,true)} disabled={blocked}>研究这条线索<ChevronRight size={15}/></button></section></aside></div><div className="lower-financial">{financialSection}</div></>}
  {tab==="financial"&&<>{financialSection}<div className="section-heading"><div><h2>行情与估值</h2><p>授权模式可请求近半年日线与当前估值</p></div><button className="secondary-button" disabled={blocked} onClick={()=>run(QUESTIONS[3])}>研究行情</button></div><section className="panel">{result.prices.length?<div className="chart"><ResponsiveContainer width="100%" height="100%" minWidth={0} initialDimension={{width:320,height:260}}><LineChart data={result.prices}><CartesianGrid vertical={false}/><XAxis dataKey="date" minTickGap={60}/><YAxis domain={["auto","auto"]}/><Tooltip/><Line dataKey="close" name="前复权收盘价 / 元" stroke="#7566d8" dot={false}/></LineChart></ResponsiveContainer></div>:<Empty title="行情区间尚不可验证">未获得明确复权口径的真实日线。接入后才计算历史收益、年化波动与最大回撤。</Empty>}</section></>}
  {tab==="peers"&&<><div className="section-heading"><div><h2>同行比较</h2><p>同一半年累计口径 · 样本比较不代表行业排名</p></div><button className="primary-button" disabled={blocked} onClick={()=>run(PEER_QUESTION)}>研究同行差异</button></div><section className="panel table-panel"><div className="table-scroll"><table><thead><tr><th>公司 / 报告期</th><th>营业收入 / 亿元</th><th>归母净利润 / 亿元</th><th>经营现金流 / 亿元</th><th>ROE / %</th><th>披露日期</th></tr></thead><tbody>{result.peers.map(r=><tr key={r.company_code} className={r.company_code==="000333.SZ"?"primary-row":""}><td><b>{r.company_name}</b><small>{r.company_code} · {pLabel(r.period)}</small></td>{["revenue","parent_profit","ocf","roe"].map(k=><td key={k}>{fmt(r.values[k],k==="roe"?"%":"亿元")}</td>)}<td>{r.published_at}</td></tr>)}</tbody></table></div><p className="footnote">美的含多元 ToB 业务，格力的业务结构不同。合并范围与 ROE 基数影响可比性。海尔尚未接入，未生成占位数字。</p></section><section className="panel"><Empty title={result.valuations.length?"估值数据已进入证据库":"同行估值暂不可验证"}>需要同一统计时点 PE TTM、PB MRQ。负值不按低估排序；没有历史序列不计算估值百分位。</Empty></section></>}
  {tab==="evidence"&&<><div className="section-heading"><div><h2>证据库</h2><p>{evidence.length} 条当前研究证据 · 事实类别与方向独立记录</p></div><label className="evidence-search"><Search size={16}/><input aria-label="搜索证据" value={search} onChange={e=>setSearch(e.target.value)} placeholder="搜索指标或证据 ID"/></label></div>{filters}<div className="evidence-grid library-grid">{cards(visible)}</div>{!visible.length&&<Empty title="没有匹配证据">换个关键词，或从入口提出新问题。</Empty>}</>}
  {tab==="data"&&<><div className="section-heading"><div><h2>来源、口径与能力边界</h2><p>数据获取、指标计算、模型解释分别记录</p></div></div><section className="panel data-warnings"><h3><AlertTriangle size={18}/>当前限制</h3>{result.warnings.map((w,i)=><p key={i}>{w}</p>)}</section><div className="charts-grid"><section className="panel method-card"><ShieldCheck size={23}/><h3>确定性程序做什么</h3><p>单位标准化、同口径同比、利润比率、现金覆盖代理、历史波动与回撤、时间及来源冲突检查。</p><h4>AI 做什么</h4><p>配置后理解问题、选择维度，基于证据解读并生成追问。数字必须绑定证据，引用不存在的 ID 会被拦截。</p></section><section className="panel method-card"><Layers3 size={23}/><h3>两种“矛盾”分开处理</h3><p><b>信号张力：</b>不同指标表达不同信号，例如利润增速快于现金流。</p><p><b>来源冲突：</b>同公司、同期次、同字段有不同数值，涉及数字停止进入正常结论。</p><p>事实并不自动具有正面方向；中性原值与未知信息分别标注。</p></section></div><section className="panel sources-panel"><h3>当前真实数据来源</h3>{result.coverage.sources.map(s=><div className="source-row" key={s.id}><span className="source-file"><FileText size={21}/></span><div><b>{s.title}</b><p>PDF 第 {s.page??"—"} 页 · 原单位 {s.unit} · 采集 {s.retrieved_at.slice(0,10)}</p>{s.sha256&&<code>SHA-256 {s.sha256}</code>}</div><a href={`${s.url}${s.page?`#page=${s.page}`:""}`} target="_blank" rel="noreferrer">原始来源<ExternalLink size={14}/></a></div>)}</section><section className="panel method-card"><h3>缓存与授权</h3><p>快照只保存公开会计事实、来源、时间与文件哈希，不公开完整报告。七天未重新采集提示缓存陈旧；期末超过两百天提示报告滞后。摘要无法替代全文。</p><p>扶摇凭证仅在服务端使用。授权数据不写入公开仓库，展示与再分发范围仍需账户持有人核实。iFinD 未授权，未宣称已接入。</p><p>模型格式校验不等于语义正确或因果验证。候选人需独立复核关键数字与结论。</p></section></>}
  <footer className="main-footer"><ShieldCheck size={14}/>{result.disclaimer}<span>StockInsight AI · Evidence first</span></footer></main></div>
  {drawer&&<div className="overlay" onClick={()=>setDrawer(null)}><aside className="evidence-drawer" role="dialog" aria-modal="true" aria-labelledby="evidence-title" tabIndex={-1} ref={dialog} onClick={e=>e.stopPropagation()}><div className="drawer-heading"><span><Layers3 size={18}/>证据详情</span><button className="icon-button" aria-label="关闭证据详情" onClick={()=>setDrawer(null)}><X size={21}/></button></div><div className="drawer-content"><div className="drawer-badges"><Badge type={drawer.claim_type}/><span className="soft-tag">{D[drawer.dimension]}</span>{drawer.conflict_kind&&<span className="soft-tag">{drawer.conflict_kind==="SIGNAL_TENSION"?"经营信号张力":"来源数据冲突"}</span>}</div><h2 id="evidence-title">{drawer.title}</h2><div className="drawer-value">{drawer.display_value}</div><code className="evidence-id">{drawer.evidence_id}</code><p className="drawer-note">{drawer.note}</p><dl className="evidence-meta"><div><dt>报告期</dt><dd>{drawer.report_period} · {drawer.period_basis==="POINT_IN_TIME"?"期末余额":"半年累计"}</dd></div><div><dt>验证状态</dt><dd>{drawer.verification_status}</dd></div><div><dt>获取时间</dt><dd>{drawer.retrieved_at}</dd></div><div><dt>行情区间</dt><dd>{drawer.market_date_range?.join(" 至 ")??"不适用"}</dd></div></dl><h3>计算与统计口径</h3><p className="formula">{drawer.calculation_method}</p><h3>原始证据输入</h3>{drawer.inputs.length?drawer.inputs.map((i,index)=><div className="raw-input" key={index}><div><b>{i.report_period} · {i.company_code}</b><span>{i.source_column}</span></div><p>{i.source_field}</p><strong>{raw(i.raw_value)}<small> {i.raw_unit}</small></strong><div className="raw-meta">披露 {i.published_at} · {i.source_page?`PDF 第 ${i.source_page} 页`:"授权 API 字段"}</div>{i.source_url&&<a href={`${i.source_url}${i.source_page?`#page=${i.source_page}`:""}`} target="_blank" rel="noreferrer">查看原始来源<ExternalLink size={13}/></a>}</div>):<div className="missing-input"><CircleHelp size={19}/><p>没有足以验证此项的数据；缺失信息不按零处理。</p></div>}{drawer.limitations.map(l=><p className="error-text" key={l}>{l}</p>)}<div className="drawer-research"><h3>把这条证据带入下一步</h3><button className={selected.includes(drawer.evidence_id)?"secondary-button":"primary-button"} onClick={()=>toggle(drawer.evidence_id)}>{selected.includes(drawer.evidence_id)?<Check size={16}/>:<BookOpen size={16}/>} {selected.includes(drawer.evidence_id)?"已加入追问上下文":"加入追问上下文"}</button><p>追问保留当前问题、维度与已选证据。</p><button className="text-button" onClick={()=>{if(!selected.includes(drawer.evidence_id))setSelected(s=>[...s.slice(-11),drawer.evidence_id]);setDrawer(null);setQuestion("造成这种差异的可能原因是什么？");setTab("research");setTimeout(()=>textarea.current?.focus(),50);}}>继续追问原因<ChevronRight size={14}/></button></div></div></aside></div>}
  {settings&&<div className="overlay settings-overlay" onClick={()=>setSettings(false)}><div className="settings-dialog" ref={settingsDialog} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby="settings-title" onClick={e=>e.stopPropagation()}><div className="drawer-heading"><h2 id="settings-title">数据与 AI 连接</h2><button className="icon-button" aria-label="关闭设置" onClick={()=>setSettings(false)}><X size={21}/></button></div><p>公开财报可直接查看。AI 研究需提交者私下提供独立站点口令；如未收到，请联系提交者。API 密钥仅在服务端配置。</p><div className="connection"><Database size={19}/><span>扶摇金融数据</span><b>{status.financial_configured?"已配置":"未配置"}</b></div><div className="connection"><Sparkles size={19}/><span>真实语言模型</span><b>{status.model_configured?`${status.model_provider??"AI"} 已配置`:"未配置"}</b></div><p>{result.engine==="llm"?`本次研究已完成真实模型规划与证据解读，并通过引用及数字检查。模型：${result.model_usage?.model??status.model??"已调用"}。`:status.model_configured?"模型已配置。填写访问口令并开始研究后，按本次调用结果显示成功或失败。":"尚未配置真实模型，当前使用规则研究。"}</p><label className="settings-label">站点访问口令<input type="password" autoComplete="off" value={access} onChange={e=>setAccess(e.target.value)} placeholder="维护者提供的口令（不是 API Key）"/></label><small>口令仅保留在本页内存中，刷新即清除。规则研究不会冒充 AI 诊断。</small><button className="primary-button" onClick={()=>setSettings(false)}>完成</button></div></div>}
  </div>;
}
